# Generated by Django 4.2.1 on 2023-05-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.IntegerField()),
                ('absolute_path', models.CharField(max_length=500)),
                ('filename', models.CharField(max_length=300)),
            ],
        ),
    ]
